app = "discord-checkers-server"
primary_region = "ams"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true

[[services.ports]]
  handlers = ["http", "tls"]
  port = 443
